version: 1
disable_existing_loggers: false


formatters:
  simple:
    format: '%(asctime)s,%(levelname)s,%(message)s'


handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  all:
    class: util.MakeFileHandler.MakeFileHandler
    level: DEBUG
    formatter: simple
    when: midnight
    filename: ./logs/logging.log

root:
  level: INFO
  handlers: [ all,console ]
  propagate: false